### ISSUE TITLE
Structure Section

### ISSUE THREAD

**Issue by pauldipietro** [defenseunicorns/uds-docs#3]
- [x] #16
- [x] #17
- [x] #18
- [x] #19
```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/uds-docs-refresh/issues/16
- [ ] https://github.com/defenseunicorns/uds-docs-refresh/issues/17
- [ ] https://github.com/defenseunicorns/uds-docs-refresh/issues/18
- [ ] https://github.com/defenseunicorns/uds-docs-refresh/issues/19
```
