### ISSUE TITLE
Bundles Section (Reference)

### ISSUE THREAD

**Issue by pauldipietro** [defenseunicorns/uds-docs#47]
```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/uds-docs-refresh/issues/48
- [ ] https://github.com/defenseunicorns/uds-docs-refresh/issues/49
- [ ] https://github.com/defenseunicorns/uds-docs-refresh/issues/50
- [ ] https://github.com/defenseunicorns/uds-docs-refresh/issues/51
```
