### ISSUE TITLE
Tutorials Section

### ISSUE THREAD

**Issue by pauldipietro** [defenseunicorns/uds-docs#6]
- [x] #62
```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/uds-docs-refresh/issues/62
- [ ] https://github.com/defenseunicorns/uds-docs-refresh/issues/97
- [ ] https://github.com/defenseunicorns/uds-docs-refresh/issues/98
- [ ] https://github.com/defenseunicorns/uds-docs-refresh/issues/99
```
